pipeline {
    agent {
        docker { image 'maven:3-jdk-8-alpine' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
