pipeline {
    agent any
    stages {
        stage('one: find the dockerfile') {
            steps {
                dir("cidr_convert_api/java/"){
                sh 'echo "step"'
            }
            }
        }
        stage('second step'){
            steps{
            sh 'echo "where"'
            }   
        }
        stage('third')
        {
            steps{
            sh 'echo "bruh"'
            }
        }
    }
}

