pipeline {
    agent any
    stages {
        stage('one: find the dockerfile') {
            steps {
                sh 'echo "step"'
            }
        }
        stage('second step'){
            sh 'echo "where"'

        }
        stage('third')
        {
            sh 'echo "bruh"'
        }
    }
}

