pipeline {
	agent any
	environment {
		SONAR_TOKEN = credentials("sonarcloud")
	}
	stages {
		stage('step one: building') {
			steps {
				dir("cidr_convert_api/java/cidr-api") {
					script {
						sh 'pwd'
						sh 'mvn package'
						}
					}	
				}
			} 

		stage('step two: analysis') {
			steps {
				dir("cidr_convert_api/java/cidr-api/") {
				sh 'pwd'
				sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar' } 
				}
			}
		stage('step three: linting') {
			steps {
				dir("cidr_convert_api/java/cidr-api/") {
				sh 'pwd'
				sh 'mvn pmd:pmd' } 
				dir("cidr_convert_api/java/cidr-api/target") {
				sh 'cat pmd.xml' } 
				}
			}
			
		stage('step four: unit test') {
			steps {
				dir("cidr_convert_api/java/cidr-api/") 
				{ sh 'mvn clean test' 
				 sh 'mvn test' }
				
					script {
					try {
						junit 'target/surefire-reports/TEST-*.xml'	
   					} catch (Exception e) {
      					echo 'still connecting'
  						}
					}
				}
			}
			
			stage('Docker') {
				steps {
					sh 'echo "CREATE THE LISTENING ON LOCAL HOST 8000 "'
     
                }
   
			}
		
    }
}
 
